### ISSUE TITLE
Open-source?

### ISSUE THREAD

**Issue by waltonfuture** [BIDS-Xu-Lab/Me-LLaMA#2]
Any plan for open-sourced models?

**Comment by Kaishu-Sahu** [comment]
+1

**Comment by gnjm111** [comment]
+1

**Comment by gfr3007** [comment]
+1

Me Too

**Comment by BerkBytes** [comment]
+1

**Comment by jiminHuang** [comment]
Hi All, our models have just been released in Physionet. Thanks!

**Comment by jiminHuang** [comment]
Please check our latest README. Thanks for your patience!
